apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-benchmark.fullname" . }}-nodeexporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-benchmark.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    job: nodeexporter
    {{ include "prometheus-benchmark.selectorLabels" . | nindent 4 }}
  ports:
  - port: 9102
    targetPort: nginx
