apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "prometheus-benchmark.fullname" . }}-alertmanager-cm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-benchmark.labels" . | nindent 4 }}
data:
  alertmanager.yml: |
    route:
      receiver: blackhole
    receivers:
    - name: blackhole
