apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "prometheus-benchmark.fullname" . }}-vmalert-cm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-benchmark.labels" . | nindent 4 }}
data:
  alerts.yml: |
{{ .Files.Get "files/alerts.yaml" | indent 4}}
